"""empty message

Revision ID: 277c624678df
Revises: 
Create Date: 2020-12-07 18:19:01.288543

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '277c624678df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_link_model',
    sa.Column('supply_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(length=120), nullable=True),
    sa.Column('social_link', sqlalchemy_utils.types.url.URLType(), nullable=True),
    sa.PrimaryKeyConstraint('supply_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('social_link_model')
    # ### end Alembic commands ###
